export const UPDATE_CURRENT_CHAT = 'UPDATE_CURRENT_CHAT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const TOGGLE_CONTACT_SIDEBAR = 'TOGGLE_CONTACT_SIDEBAR';
export const CHANGE_CURRENT_THEME = 'CHANGE_CURRENT_THEME';